title: Notes
description: For everlasting memory.
lang: ru
version: 3.5.0

permalink: /:categories/:year/:month/:day/:title:output_ext

sass:
  style: :expanded # Replace to :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
