title: Notes
description: For everlasting memory.
lang: ru_RU
copyright: © 2019 dini
version: 3.5.0

sass:
  style: :expanded # Replace to :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
